### PR TITLE
Added file for integrating SAWO with JWT.

### PR DESCRIPTION
**Pull request by Gauravdarkslayer**
This markdown file contains the tutorial on how one can implement JWT with SAWO SDK in the MEAN stack.

### CODE REVIEW

**Comment by SawoCommunity** [comment]
@Gauravdarkslayer can you share the sample app repository in which you have tested the code?

**Comment by Gauravdarkslayer** [comment]
@SawoCommunity Sure.

**Comment by Gauravdarkslayer** [comment]
@SawoCommunity Here it is. https://github.com/Gauravdarkslayer/SAWO-AUTH

**Comment by SawoCommunity** [comment]
Thanks a lot

**Comment by Gauravdarkslayer** [comment]
@SawoCommunity can you please specify the reason being why it's invalid

**Pull request closed without merging**
